SECTION "ROM Bank 1D", ROMX[$4000], BANK[$1D]

StringTable:
    db   "Make-up! Jewels!Dresses!  I wantit a"
    db   "ll!  Sigh...And some new    accessor"
    db   "ies     would be nice...", $FF, "Make-up! Je"
    db   "wels!Dresses!  I wantit all!  Sigh.."
    db   ".And some new    accessories     wou"
    db   "ld be nice...Oh! That Ribbon!I need "
    db   "it!  Willyou trade for mydog food?  "
    db   "         Yes  No!", $FE, "You exchanged ", $E1, " fo"
    db   "r ", $E2, "! It^s fullof juicy beef!", $FF, "Lucky! "
    db   " Thanks! Well, here^s    your ", $E2, "!", $FF, "Eh?"
    db   "!  I can^t   believe it!  Youare the"
    db   " worst!!", $FF, "I am Manbo,     child of th"
    db   "e SunFish!  Have you got an Ocarina?"
    db   "     Yes  No", $FE, "Very well...    Glub Bl"
    db   "ub Bloop!", $FF, "Ahaha!  Then I  can teach "
    db   "you mysong! Bloop!", $FF, "You^ve learned  M"
    db   "anbo^s Mambo!  When you get outof th"
    db   "e water,   play it!", $FF, "I am Manbo,     "
    db   "child of the SunFish!  When you play"
    db   " my Mambo,  you can warp to Manbo Po"
    db   "nd!  Trythis tune in thedungeons, to"
    db   "o!  Cha-cha-cha!", $FF, "Aha... You don^thav"
    db   "e an Ocarina,so...Glub glub!", $FF, "Chicken"
    db   "s these  days don^t have the fightin"
    db   "g    spirit they usedto!  In the old"
    db   " days, they couldfly, flap flap! But"
    db   " now, see?   Cluck cluck!", $FF, "Wow!  Amaz"
    db   "ing!  That rooster is actually flyin"
    db   "g!It^s just like Isaid, eh?  Have yo"
    db   "u tried to    hold him over   your h"
    db   "ead? CluckCluck!", $FF, "Wooo!  Finally! Thi"
    db   "s flying     rooster is the  greates"
    db   "t!", $FF, " Here Sleeps The Flying Rooster", $FF, "E"
    db   "nnh?  Who^s    this suspicious-looki"
    db   "ng runt?!  Okay boys, let^sget ridda"
    db   " him!", $FF, "You must be an  assassin sent "
    db   "byMadam MeowMeow  to rescue the   mu"
    db   "tt!  You came here to get me, but it"
    db   " is I who will get you!!", $FF, "Oh, #####. "
    db   " I   often come to   this village to"
    db   " sing, too!  It  seems that just abo"
    db   "ut everyone  loves my ^Balladof the "
    db   "Wind     Fish!^  #####,  what is you"
    db   "r    favorite song?", $FF, "Please, don^t   "
    db   "ever forget thissong...or me...", $FF, "Than"
    db   "k you for   everything!     #####, y"
    db   "ou are  the kindest boy I know.  One"
    db   " dayI made a wish tothe Wind Fish..."
    db   "What was the    wish?  It was...No, "
    db   "it^s secret!", $FF, "#####, some day you wil"
    db   "l leave  this island...  I just know"
    db   " it  in my heart...  ...Don^t ever  "
    db   " forget me... If you do, I^ll    nev"
    db   "er forgive   you!", $FF, "... ... ... ... It"
    db   " seems to be  totally absorbedin Mar"
    db   "in^s song!", $FF, "They say the    ^Ballad o"
    db   "f the  Wind Fish^ is a song of awake"
    db   "n- ing.  I wonder, if the Wind Fishw"
    db   "akes up, will  he make my wish come "
    db   "true?", $FF, "Eh?  You want meto go in there"
    db   "? No, I think I^llwait out here...Ta"
    db   "ke care of    yourself, #####!", $FF, "Ahhh!"
    db   "  Ahhh, youare a bad boy,  #####!", $FF, "He"
    db   "re^s some     bonus treatment!Behold"
    db   "!  Your   Hearts are full!", $FF, "Ya, I am "
    db   "Schule Donavitch!  Zee mermaid statu"
    db   "e  by zee bay iz mymasterpiece! ...T"
    db   "o tell you zee truth, zis werk iz no"
    db   "t complete!Zee art, it^z...difficult"
    db   " for   you to grasp, izit not?", $FF, "  THE"
    db   " MOURNING       MERMAID        By SC"
    db   "HULE   ? ...A scale is missing...", $FF, "Se"
    db   "ashell Mansion", $FF, "Entrance to       Yar"
    db   "na Desert ", $F3, $FF, "   Mysterious        For"
    db   "est      (It^s a little  bit mysteri"
    db   "ous)", $FF, "Do you want to  challenge the  "
    db   " river rapids on a raft?  Proceedto "
    db   "the office atonce, please!", $FF, "East ", $F3, " Uk"
    db   "uku           Prairie  Farther East "
    db   "     Animal Village", $FF, "Mt. Tamaranch   "
    db   $FF, $F3, " Tail Cave     ", $F1, " Toronbo Shores", $FF, $F3, " "
    db   "Gopongo Swamp ", $F1, " Mysterious      Fore"
    db   "st", $FF, "Beware of floorswith cracks!  A h"
    db   "eavy person    should not standon th"
    db   "em!", $FF, "Telephone Booth ", $FF, "     DANGER!   "
    db   "     Keep out!   (Except BowWow)", $FF, $F1, " G"
    db   "O THIS WAY", $FF, $F0, " GO THIS WAY", $FF, $F3, " GO THIS W"
    db   "AY", $FF, $F2, " GO THIS WAY", $FF, " TRY AGAIN FROM    "
    db   "THE START", $FF, "GREAT!  YOU DID IT!  YOUR "
    db   "REWARDIS ", $F3, " THIS WAY!", $FF, "GONE ON TOUR   "
    db   "          MAMU", $FF, $F3, " Crazy Tracy   ", $F1, " Man"
    db   "bo^s Pond", $FF, $F3, " Animal Village", $F1, " Martha^s"
    db   " Bay", $FF, $F3, " Welcome to the Animal Village"
    db   "!", $FF, $F3, " Cemetary      ", $F1, " Ukuku Prairie ", $FF, "T"
    db   "al Tal Heights", $FF, $F3, " Tamaranch Mt. ", $F2, " Gop"
    db   "onga Swamp ", $FF, "MUSIC, THE FISH STIRS IN"
    db   " THE EGGYOU ARE THERE...", $FF, "THE WIND FI"
    db   "SH INNAME ONLY, FOR  IT IS NEITHER.", $FF
    db   "IN SOIL SLEEPS  SECRETS, BENEATHYOUR"
    db   " SOLES...", $FF, "IN SOIL SLEEPS  SECRETS, B"
    db   "ENEATHYOUR SOLES...", $FF, "AROUND HERE,    "
    db   "SECRETS ARE NIGH", $FF, "SECRETS ARE LIKEWAT"
    db   "ER WHEN IT   COMES TO BRIDGES", $FF, "NOW YO"
    db   "U NEED    LOOK FAR FOR    A SECRET.."
    db   ".", $FF, "THE WIND FISH   SLUMBERS LONG...TH"
    db   "E HERO^S LIFE GONE...", $FF, "SEA BEARS FOAM"
    db   ", SLEEP BEARS     DREAMS. BOTH ENDIN"
    db   " THE SAME WAY CRASSSH!", $FF, "Oh?!  #####, "
    db   "I  see ya have a   nice stick...   C"
    db   "an I borrow it for a second?       C"
    db   "an  Can^t", $FE, $E4, " became the    honeycomb "
    db   $E5, "!    You^re not sure how it happene"
    db   "d,but take it!", $FF, "Hmmm, #####, youare m"
    db   "ean!", $FF, "Beware of Sea   Urchins!  Don^t"
    db   " touch them with your bare hands!", $FF, "I "
    db   "was hungry    somethin^ fierceso I w"
    db   "ent and   got bananas at  the beach."
    db   "..    #####, if you   want some, you"
    db   "  should go and   get some!", $FF, "Welcome "
    db   "to      Sale^s House O^ Bananas!  I^"
    db   "m   Sale, this is myhouse! Actually,"
    db   "my hobby is col-lecting rare andunus"
    db   "ual canned  food. My brotheris an ar"
    db   "tist, soI guess strange hobbies run "
    db   "in  the family!", $FF, "What^s that you have"
    db   "?!  It^s    canned food! Forheaven^s"
    db   " sake,  man, give that ", $E2, "to ME!!  PLE"
    db   "ASE!He^s hysterical!What do you do? "
    db   "    Give Don^t", $FE, "Oh thank you!   I^ll "
    db   "take that!", $FF, "I don^t suppose it would "
    db   "do any good to beg?    Well, if you "
    db   "   change your     mind, tell me.", $FF, "  "
    db   "MUNCH MUNCH!! ... ... ... ... That w"
    db   "as great! I know it^s not a fair tra"
    db   "de,   but here^s some bananas! YUM.."
    db   ".", $FF, "You gave him ", $E2, "  and got bananas ", $E3, " "
    db   "in return!    Good deal!", $FF, "Thank you a"
    db   "gain!That was yummy!", $FF, "Hey friend! Hav"
    db   "eyou ever ridden the rapids on a raf"
    db   "t?  You can, near Tal Tal    Heights"
    db   "!  You   ought to try it!", $FF, "Rik^m rak^"
    db   "m! I  ran out of      ingredients!  "
    db   "IfI had honey, I  could make this fi"
    db   "t for a king!", $FF, "Hi ho! Hey you! Is tha"
    db   "t possiblya ", $E5, " you have?   I just ran"
    db   " out! Will you swap itfor a pineappl"
    db   "e?    Yes  No", $FE, "You exchanged ", $E5, " for ", $E6, "!"
    db   "  It^s notas sweet, but itis delicio"
    db   "us!   ", $FF, "That^s a crying shame, but I "
    db   "   realize those   are a rare      d"
    db   "elicacy!", $FF, "Hi ho! Yeah, I  know, that "
    db   "tub  of goo is asleepright in the wa"
    db   "yto Yarna Desert!Once he^s asleephe "
    db   "won^t budge  for a loooooonngtime.  "
    db   "But hey! Take Little     Marin and w"
    db   "ake  him up with her song!  That slo"
    db   "bwould wake up   with a jump if  he "
    db   "heard her    sing, for sure! Heh heh"
    db   " heh!", $FF, "My ultimate planis to open a  "
    db   "  branch in Mabe  Village!", $FF, "HI HO!  L"
    db   "ittle  Marin!  Welcome!... ... ... ."
    db   ".. Oh, shucks!  Youare here too... S"
    db   "orry...", $FF, "Oh, #####, I^m  glad you fou"
    db   "nd  this place.     Will you stay   "
    db   "and talk to me  for a while?        "
    db   "Yes! No...", $FE, "Okay, I^ll just watch the"
    db   " waves for a while...", $FF, "At the beach.."
    db   ".  Marin  ", $DE, $FF, "I wonder where  these co"
    db   "conut   trees come from?...Tarin say"
    db   "s   there is nothingbeyond the sea, "
    db   "but I believe   there must be   some"
    db   "thing over  there...  When Idiscover"
    db   "ed you, #####, my heart skipped a be"
    db   "at! I thought, this person has come "
    db   "to give us a    message...", $FF, "... ... ."
    db   ".. ... ... ... ... ... If I was a se"
    db   "a  gull, I would   fly as far as I c"
    db   "ould!  I would fly to far away place"
    db   "s and sing for many people!...If I w"
    db   "ish to the Wind Fish,  I wonder if m"
    db   "y  dream will come true... ... ...", $FF, "H"
    db   "ey!  Are you   listening?      #####"
    db   ", are you  listening to me?    Yeah "
    db   "No...", $FE, "I want to know  everything abo"
    db   "utyou...Err...Uhh,Ha ha ha ha!", $FF, "Hunh?"
    db   " The walruswants me to go  to him?  "
    db   "It     doesn^t matter, I will go wit"
    db   "h  you to him...", $FF, "Unnnngh! Owwwww!..."
    db   " ... ... ... I^ve sure lost  my tast"
    db   "e for    honey!", $FF, "Humph! Your headis a"
    db   "lways in theclouds! Will youplease l"
    db   "isten tome next time?!", $FF, "ZZZ ZZZ ZZZ Z"
    db   "ZZ  ... ", $DE, " ... ", $DE, " ...", $FF, "Yes, it^s that  "
    db   "lazy walrus!    Shall we give   him "
    db   "a little    surprise?           Yes "
    db   " No...", $FE, "Aha ha ha!  Wow!He certainly "
    db   "   woke with a     start!", $FF, "Hunh?  Oh,"
    db   " he^s calling me...   It^s the same "
    db   "asalways... Ha ha!", $FF, "You^re right, itw"
    db   "ould be mean towake him up now!Let^s"
    db   " let him   sleep some more!", $FF, "#####, I"
    db   "^m goingto the Animal   Village!  Pl"
    db   "easedrop by, okay?", $FF, "Arfh! Arfh! Arf! "
    db   $DE, "  ", $DE, "!  ", $DE, "   ", $DE, "!  ..... ", $DD, "?? ", $FF, "It^s no us"
    db   "e,    little buddy!  Afish took my  "
    db   "  hook... I keep  casting my line in"
    db   "to the water, but I haven^t   got a "
    db   "bite... I thought this    would happ"
    db   "en...", $FF, "Oh! What is thatyou have in yo"
    db   "urhand?  It^s not a fishing hook, is"
    db   " it?  You had better let me   have i"
    db   "t.  I^ll  give you my nextcatch if y"
    db   "ou letme have it...       Okay No", $FE, "Al"
    db   "l right, boy, feast your eyes on a d"
    db   "isplay of fishing skill!", $FF, "You should "
    db   "be   more kind to me!I thought we   "
    db   " were buddies!", $FF, "Whoooah nellie!!It^s "
    db   "a big one!!Big! Big! Yaaah!", $FF, "The ", $E9, " be"
    db   "came a  necklace ", $EA, "!     L-l-lucky!", $FF, "I"
    db   " can^t wait to see what I^ll   catch"
    db   " next!", $FF, "When I was swim-ming in the b"
    db   "ay,the waves took avery important  n"
    db   "ecklace from   around my neck! If yo"
    db   "u find it, I will let you  take a sc"
    db   "ale    from my tail!   ", $FF, "I have alrea"
    db   "dy  looked around   here!", $FF, "Ahh!  That"
    db   "^s it!That^s my neck- lace!  Give it"
    db   "! Give it back!  Iwill give you a sc"
    db   "ale as I said!    Give Keep", $FE, "Promise!"
    db   "  You^llonly take one!", $FF, "You are heart"
    db   "-  less and cruel!", $FF, "You returned then"
    db   "ecklace ", $EA, " and  got a scale ", $EB, " ofthe m"
    db   "ermaid^s   tail.  How will you use t"
    db   "his?", $FF, "An artist once  asked me to pos"
    db   "efor him, and he wanted a scale, too"
    db   "...  Can the legend of the   Magnify"
    db   "ing Lens be true...?", $FF, "Richard^s Villa"
    db   " ", $FF, "Kanalet Castle  10 Min. ", $F3, " ", $F0, $FF, "Kanale"
    db   "t Castle  5 Min. ", $F3, $FF, "Kanalet Castle  5"
    db   "0 Paces ", $F0, $FF, "^BRRING! BRRING! BRRING! C"
    db   "LICK! Yeees!  It^s theBucket Mouse! "
    db   "  Thanks for call-ing! ...Well... CL"
    db   "ICK!^  ??? ...You must have   dialed"
    db   " a wrong  number...", $FF, "Oh!  It^s a big "
    db   "one!  And it hasa Piece of      Hear"
    db   "t, too!  Youget a 20 Rupee  prize on"
    db   " top of that! Try again?    Yes  No", $FE
    db   "Oh!  It^s a big one!  And it hasa Pi"
    db   "ece of      Heart, too!  Youhave com"
    db   "pleted  another Heart   Container!  "
    db   "On  top of that, youget a 20 Rupee  "
    db   "prize! Want to  try again?          "
    db   "Yes  No", $FE, " ^How To Handle    Your Shie"
    db   "ld     Like A Pro!^ Read this book? "
    db   "    Read Don^t", $FE, "^If you hold theButto"
    db   "n down, youcan defend your-self from"
    db   " enemy attacks, and youcan fillip so"
    db   "me enemies, too... Besides the     s"
    db   "tandard shield there is also a mirro"
    db   "red varietywhich can defendagainst b"
    db   "eams!^", $FF, " ^Selecting The    Item That^"
    db   "s    Right For You^Read this book?  "
    db   "   Read Don^t", $FE, "^You can select your f"
    db   "avorite   item for the A  and B Butt"
    db   "ons onthe Sub-Screen. Using differen"
    db   "t items, you can  fight without a sw"
    db   "ord!  Try manydifferent thingsto fin"
    db   "d what^s  right for you!^", $FF, " ^Auto Map"
    db   " and  Memo Guide Book^Read this book"
    db   "?     Read Don^t", $FE, "^You can see an isl"
    db   "and map by   pressing the    SELECT "
    db   "Button.  The dark parts  of the map "
    db   "are  places you have not yet visited"
    db   ".Move the cursor and press the A But"
    db   "ton to get   more informationabout a"
    db   "n area,  or to replay themessage you"
    db   " got there...^  Ahhh!How convenient!"
    db   $FF, " ^Secrets Of The Whirling Blade^Rea"
    db   "d this book?     Read Don^t", $FE, "^The Whi"
    db   "rling   Blade technique has been han"
    db   "ded down from gener-ation to gener- "
    db   "ation by the    family of the   hero"
    db   ". To use it,hold down the   Sword Bu"
    db   "tton andbuild up your   power.  When"
    db   " youhave enough, youcan release the "
    db   "Button!  Can youmaster this?^", $FF, "^The P"
    db   "roperties   Of Warp Holes^Read this "
    db   "book?     Read Don^t", $FE, "^There are some"
    db   " Warp Holes on   Koholint Island.You"
    db   " can warp to and fro using   these h"
    db   "oles.  Ifyou jump into   the Warp Ho"
    db   "le   at which you    arrived, you   "
    db   " will go to the  next one in the seq"
    db   "uence.  You  can only warp toa hole "
    db   "you have seen with your  own eyes..."
    db   "^", $FF, "^Fun With Bombs^Read this book?   "
    db   "  Read Don^t", $FE, "^After you put aBomb do"
    db   "wn, you  can pick it up  by pressing"
    db   " the Button again.   You can then   "
    db   " throw it by     pushing the     But"
    db   "ton one more time.  Did you  know th"
    db   "at?^", $FF, "   ^Atlas Of    Koholint Island"
    db   "^You can move thecursor and look up "
    db   "the name of aplace...  Do youwant to"
    db   " look at this map?           Look Do"
    db   "n^t", $FE, " ^Dark Secrets    And Mysteries "
    db   "   Of Koholint^ Do you really   want"
    db   " to read it?    Yes! N-No", $FE, "Gasp! Wha-"
    db   "What^sthis! ... ...   You can^t read"
    db   "  the tiny print  without the aid of"
    db   " a magnifying glass...", $FF, "...my grave.."
    db   ".  ...take me...   ...my grave...", $FF, ".."
    db   ".the house...  ...take me...  ...the"
    db   " house... ...at the bay...", $FF, "...N-N-No"
    db   "!...   ...N-not there!", $FF, "   ...Here!.."
    db   ".     ...enter...   ...my house...", $FF, " "
    db   "...Nostalgia... ...unchanged... ...b"
    db   "oo hoo...", $FF, "  ...Enough...   ...cemeta"
    db   "ry...   ...take me...  ...my grave.."
    db   ".", $FF, "...Thank you...  ...a jar...    .."
    db   ".in my home......look inside.....bye"
    db   "...bye...", $FF, "Round and round,the passag"
    db   "eways of the Egg...   ", $F2, " ", $F2, " ", $F0, " ", $F3, " ", $F3, " ", $F0, " ", $F2, " "
    db   $F0, " ??  ...Hmmmmmm, this book reeks of"
    db   " secrets...", $FF, "Round and round,the pass"
    db   "ageways of the Egg...   ", $F3, " ", $F0, " ", $F0, " ", $F3, " ", $F0, " ", $F0, " "
    db   $F3, " ", $F0, " ??  ...Hmmmmmm, this book reeks "
    db   "of secrets...", $FF, "Round and round,the pa"
    db   "ssageways of the Egg...   ", $F2, " ", $F0, " ", $F3, " ", $F0, " ", $F2, " "
    db   $F0, " ", $F3, " ", $F0, " ??  ...Hmmmmmm, this book reek"
    db   "s of secrets...", $FF, "Round and round,the "
    db   "passageways of the Egg...   ", $F3, " ", $F3, " ", $F3, " ", $F3, " "
    db   $F0, " ", $F0, " ", $F0, " ", $F0, " ??  ...Hmmmmmm, this book re"
    db   "eks of secrets...", $FF, "...You^re late! I "
    db   "thought you^d never come back!", $FF, "...EE"
    db   "EK!  You^rehurt!  Arrrgh!  Don^t be "
    db   "so     reckless!", $FF, "#####! You^re   bac"
    db   "k!  Are you  hurt?", $FF, "...You idiot!   I"
    db   " told you this would happen... Eh?! "
    db   " What?  I  didn^t say any- thing, re"
    db   "ally!", $FF, "Hey buddy!  It^sserious!  Yeah"
    db   ", really serious!!Yeah, it is!    Th"
    db   "e Moblins cameto the village! Yeah, "
    db   "that^s    right!  A whole gang of Mo"
    db   "blins!Then... It^s forreal!  They al"
    db   "l went to the     house...  Yeah, th"
    db   "at house, and then they did   someth"
    db   "ing at BowWow^s house!!   It was a r"
    db   "eally bad scene, with the M-m-moblin"
    db   "s!So, I mean, ahh!... ... ... ... .."
    db   ". ... ... ... It might be     faster"
    db   " to find  out for yourselfwhat happe"
    db   "ned!", $FF, "I found a good  item washed up "
    db   " on the beach... I^ll trade it toyou"
    db   " for what youhave in your B  Button."
    db   "..           Okay No", $FE, "Okay, let^s do "
    db   " it!  When you   don^t want the  Boo"
    db   "merang any   more, come back!", $FF, "Oh, ye"
    db   "ah, uh... okay, whatever.", $FF, "You got th"
    db   "e     Boomerang in    exchange for t"
    db   "heitem you had.", $FF, "Give me back theBoom"
    db   "erang, I begyou! I^ll returnthe item"
    db   " you    gave to me!         Okay Not"
    db   " Now", $FE, "The item came   back to you. Yo"
    db   "ureturned the    Boomerang.", $FF, "Ah... Do"
    db   "n^t giveme that item... How about so"
    db   "me- thing else?", $FF, "Hunh?  A keyholehere"
    db   "?  It says, ^Tale Keyhole^", $FF, "Hunh?  A "
    db   "keyholehere?  It says, ^Slime Keyhol"
    db   "e^", $FF, "Hunh?  A keyholehere?  It says, ^"
    db   "Angler Keyhole^", $FF, "Hunh?  A keyholehere"
    db   "?  It says, ^Bird Keyhole^", $FF, "Hunh?  A "
    db   "keyholehere?  It says, ^Face Keyhole"
    db   "^", $FF, "Somebody, HELP!", $FF, "Hey!  #####!    So"
    db   "me monsters   put me up here! What s"
    db   "hould I   do?!  I^m afraidof heights"
    db   "!!", $FF, "Yow!  That was asurprise! #####,t"
    db   "hank you!", $FF, "... ... ... ... ... ... .."
    db   ". ... Say... #####... ", $FF, "Uhh... I don^"
    db   "t  know how to say this... but...", $FF, "Hu"
    db   "nh?!  Tarin??!... ... ... ... Uh... "
    db   "Nevermind,I... I gotta go!", $FF, "MAAAAAAAR"
    db   "INNNN!!", $FF, "^BRRING! BRRING!This is Ulri"
    db   "ra! Oh, I heard fromgrandma that    "
    db   "there is some-  thing hidden    behi"
    db   "nd the fallsin the Tal Tal  Mountain"
    db   "s.  Doesthat help?  Bye!CLICK!^", $FF, "^BRR"
    db   "ING! BRRING!Ulrira here...  Yes, whe"
    db   "n I was just a lad, I   recall seein"
    db   "g a high tower in   the mountains!  "
    db   "You should go   there!  Is that help"
    db   "ful for you?Bye! CLICK!^", $FF, "^BRRING! BR"
    db   "RING!Hello, this is  Ulrira speaking"
    db   "!#####, it^s timefor you to face the"
    db   " Egg on Mt.  Tamaranch!  Be  careful"
    db   ", #####! Bye!  CLICK!^", $FF, "^BRRING! BRRI"
    db   "NG!This is Ulrira! You^re lost in  t"
    db   "he Egg?  Hmmmm.No sir, I can^t help "
    db   "you on thatone.  How about the libra"
    db   "ry?    And hey, don^t  stop calling "
    db   "me because I didn^tknow one little a"
    db   "nswer!  CLICK!^", $FF, "^BRRING! BRRING!Ulri"
    db   "ra at your  service!  Oh?   You shou"
    db   "ld take BowWow home now,Madam MeowMe"
    db   "ow  would appreciateit! Bye! CLICK!^"
    db   $FF, "^BRRING! BRRING!Yeah, this is   Ulr"
    db   "ira!  You arestarting to liketo musi"
    db   "c, eh?   Well, a frog    named Mamu,"
    db   " who lives in the    Signpost Maze, "
    db   " might know some new songs, but  he "
    db   "charges a lotto play them!   Bye!  C"
    db   "LICK!^", $FF, "^BRRING! BRRING!Hi, it^s Ulri"
    db   "ra!You are doing   great!  Your    e"
    db   "fforts will endsoon... By the  way, "
    db   "have you   visited the Hen House on "
    db   "the    mountain?  Thereis a cave nea"
    db   "rbywith something  important in it.B"
    db   "ye!  CLICK!^", $FF, "^BRRING! BRRING!Ulrira "
    db   "speaking!Are your enemiestoo strong "
    db   "for  you?  In that   case, you bette"
    db   "rcollect all the Seashells...Justbel"
    db   "ieve in your-self and do yourbest!  "
    db   "CLICK!^", $FF, "^BRRING! BRRING!Ulrira here!"
    db   " ...Go for it!      You^re almost   "
    db   "there! I^m pull-ing for you!    Bye!"
    db   "  CLICK!^", $FF, "Yarna Desert?   There^s a "
    db   "way toget there to thesouth, but you"
    db   "  might not be    able to get     th"
    db   "rough if that lazy walrus is  in the"
    db   " way!", $FF, "Ahhh... Sigh... On such a nice"
    db   "  day, we need a  song from Marin!", $FF, "H"
    db   "ey! Did ya knowAnimal Village  and M"
    db   "abe Villageare sister      cities?  "
    db   "Yes,   even though theyaren^t large "
    db   "   enough to be    called cities...A"
    db   "nyway, I heard from a very goodsourc"
    db   "e that theyhave a Dream    Shrine in"
    db   " Mabe, and that it has something goo"
    db   "d  inside...  Is   that true?", $FF, "Lately"
    db   " there    have been a lot of monster"
    db   "s in  the area, so we can^t go to Ma"
    db   "beVillage...  I   wonder how Marinis"
    db   " doing?", $FF, "Have you heard  of the Flyin"
    db   "g   Rooster?  They  say it lived in "
    db   "Mabe Village a  long time ago...I wo"
    db   "nder if it^strue...", $FF, "Aaaah, Little   "
    db   "Marin... I want her to come backagai"
    db   "n...Her songis the best...", $FF, "I dreamed"
    db   " that  I turned into a carrot last  "
    db   "   night...  What  an odd dream...", $FF, "E"
    db   "h?  How can an animal talk?    How? "
    db   " Hey, I^m  just a rabbit,  so I don^"
    db   "t know!", $FF, "Ahhh!  It^s her!Little Marin"
    db   "!!"

    db   $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    db   $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    db   $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    db   $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    db   $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    db   $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    db   $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    db   $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    db   $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    db   $FF, $FF
